FROM golang:1.24.6-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o producer ./cmd/producer

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/producer .
CMD ["./producer"]